server {
    listen 80;
    server_name localhost;

    # Nơi chứa code frontend
    root /usr/share/nginx/html;
    index index.html;

    # Xử lý React Router: Nếu không tìm thấy file, trả về index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bắt tất cả các Request bắt đầu bằng /api và đẩy cho Backend Spring Boot
    location /api/ {
        # 'bonlai-api' là tên service của backend trong docker-compose
        proxy_pass http://bonlai-api:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
